// <auto-generated />
namespace _1150GroupAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class secee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secee));
        
        string IMigrationMetadata.Id
        {
            get { return "202105192142203_secee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
