// <auto-generated />
namespace _1150GroupAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class example : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(example));
        
        string IMigrationMetadata.Id
        {
            get { return "202105202234488_example"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
